apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-deployment
  labels:
    app: java
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java
  template:
    metadata:
      labels:
        app: java
    spec:
      containers:
      - name: java
        image: 192.168.205.141:5000/repository/app/java:22
        ports:
        - containerPort: 8090
      imagePullSecrets:
      - name: nexus
